version: '3.3'

services:
  db:
    container_name: aqib-db
    restart: unless-stopped
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./schema/init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./schema/data.sql:/docker-entrypoint-initdb.d/02_data.sql
      
